services:
    nginx:
        image: nginx:latest
        container_name: ng_nginx
        restart: always
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./etc/docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - ng_network
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: php:8.3-fpm
        container_name: ${APP_CONTAINER_NAME}
        restart: always
        tty: true
        environment:
            APP_ENV: ${APP_ENV}
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        networks:
            - ng_network
    db:
        image: mysql:8.0.25
        container_name: ng_db
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ng_db:/var/lib/mysql
        ports:
            - "3306:3306"
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - ng_network

volumes:
    ng_db:

networks:
    ng_network:
        driver: bridge